spring.application.name=Bot
bot.name=FindInform_rail_bot
bot.key=REDACTED_BOT_TOKEN
admin.chat.id=REDACTED_CHAT_ID
videos.base-dir=${user.home}/videos
logging.level.org.springframework.web=DEBUG
whisper.script=/app/pythonScript/Whisper.py
downloader.script=/app/pythonScript/Downloader.py
spring.devtools.restart.enabled=false
upload.base-url=http://REDACTED_IP
spring.servlet.multipart.max-file-size=2500MB
spring.servlet.multipart.max-request-size=2500MB
upload.dir=${user.home}/upload
app.storage.base=${user.dir}/upload/videos
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Настройки очистки файлов
cleanup.enabled=true
cleanup.retention-days=14
cleanup.schedule=0 0 2 * * ?

# Настройки планировщика
spring.task.scheduling.pool.size=2