spring.application.name=demo
bot.name = test_find_Inform_rail_bot
bot.key = REDACTED_BOT_TOKEN
admin.chat.id=REDACTED_CHAT_ID
videos.base-dir=${user.home}/videos
logging.level.org.springframework.web=DEBUG